
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/angel/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.5.0-26-generic - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/angel/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.5.0-28-generic - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/angel/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.5.0-44-generic - x86_64
...
